import type { Metadata } from "next";
import { notFound } from "next/navigation";
import Link from "next/link";
import { routes } from "@/data/routes";

export function generateStaticParams(){return routes.map((route)=>({slug:route.slug}))}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const{slug}=await params;const route=routes.find((item)=>item.slug===slug);if(!route)return{};const title=`Xe Ghép ${route.origin} – ${route.destination}`;const description=`Gửi yêu cầu xe ${route.origin} đi ${route.destination}: xe ghép, bao xe 4–7 chỗ, đón tận nơi. Xác nhận trước chuyến, đi xong mới thanh toán.`;return{title,description,alternates:{canonical:`/${route.slug}`},openGraph:{title,description,images:[]},twitter:{title,description,images:[]}}}
export default async function RouteDetail({params}:{params:Promise<{slug:string}>}){
  const{slug}=await params;const route=routes.find((item)=>item.slug===slug);if(!route)notFound();
  const faq=[{q:"Gửi yêu cầu có cần thanh toán không?",a:"Không. Phong Cách sẽ gọi xác nhận xe, giờ đón và chi phí trước chuyến. Bạn thanh toán sau khi hoàn thành chuyến đi."},{q:"Xe có đón tận nơi không?",a:"Có. Điểm đón và trả được thống nhất khi tư vấn viên gọi xác nhận chuyến."},{q:"Nên gửi yêu cầu trước bao lâu?",a:"Bạn nên gửi yêu cầu sớm để bên mình chủ động kiểm tra xe và khung giờ phù hợp."}];
  const jsonLd={"@context":"https://schema.org","@type":"FAQPage",mainEntity:faq.map((item)=>({"@type":"Question",name:item.q,acceptedAnswer:{"@type":"Answer",text:item.a}}))};
  const bookingUrl=`/?from=${encodeURIComponent(route.origin)}&to=${encodeURIComponent(route.destination)}#dat-xe`;
  return <main className="route-page"><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(jsonLd)}}/><header className="inner-header"><Link className="brand" href="/"><span className="brand-mark">PC</span><span><strong>PHONG CÁCH</strong><small>Xe ghép & bao xe liên tỉnh</small></span></Link><a className="btn btn-primary" href="tel:0987663883">☎ Gọi tư vấn</a></header><section className="route-detail-hero"><div><Link href="/tuyen-xe">← Tất cả tuyến</Link><span>{route.tag||"Có chuyến mỗi ngày"}</span><h1>Xe Ghép {route.origin}<br/><b>– {route.destination}</b></h1><p>Gửi tuyến trong một phút để bên mình kiểm tra xe ghép, bao xe 4–7 chỗ và thống nhất điểm đón phù hợp.</p><div className="route-detail-actions"><a className="btn btn-primary" href={bookingUrl}>Gửi yêu cầu tuyến này →</a><a className="btn btn-ghost" href="tel:0987663883">Gọi 0987 663 883</a></div></div><aside><span>THÔNG TIN THAM KHẢO</span><div><small>Mức giá ghép dự kiến</small><strong>{route.sharedPrice?`Từ ${Math.round(route.sharedPrice/1000)}.000đ/người`:"Liên hệ báo giá"}</strong></div><div><small>Quãng đường</small><strong>Khoảng {route.distanceKm} km</strong></div><div><small>Thời gian di chuyển</small><strong>Khoảng {Math.floor(route.durationMinutes/60)} giờ {route.durationMinutes%60||""} phút</strong></div><p>Chưa cần thanh toán. Tư vấn viên sẽ gọi xác nhận xe, giờ đón và mức giá cuối trước chuyến.</p></aside></section><section className="route-info"><div><span className="section-kicker">RÕ RÀNG TRƯỚC KHI ĐI</span><h2>Chuyến xe vừa với nhu cầu</h2><div className="route-benefits"><article><b>01</b><h3>Xe 4–7 chỗ</h3><p>Chọn xe ghép tiết kiệm hoặc bao xe riêng theo số người đi.</p></article><article><b>02</b><h3>Đón tận nơi</h3><p>Linh hoạt thống nhất điểm đón và điểm trả theo tuyến.</p></article><article><b>03</b><h3>Đi xong trả tiền</h3><p>Không thu tiền khi gửi yêu cầu; chỉ đi khi bạn đã đồng ý.</p></article></div></div><div className="faq"><span className="section-kicker">CÂU HỎI THƯỜNG GẶP</span><h2>Thông tin cần biết</h2>{faq.map((item)=><details key={item.q}><summary>{item.q}<span>＋</span></summary><p>{item.a}</p></details>)}</div></section><section className="final-cta"><div><span>TUYẾN {route.origin.toUpperCase()} – {route.destination.toUpperCase()}</span><h2>Cần bên mình kiểm tra xe?</h2><p>Gửi yêu cầu miễn phí. Tư vấn viên sẽ gọi xác nhận trước khi bạn quyết định.</p></div><a className="btn btn-white" href={bookingUrl}>Gửi yêu cầu để được gọi lại</a></section></main>
}
