import type { Metadata } from "next";
import { notFound } from "next/navigation";
import Link from "next/link";
import { routes } from "@/data/routes";

export function generateStaticParams(){return routes.map((route)=>({slug:route.slug}))}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const{slug}=await params;const route=routes.find((item)=>item.slug===slug);if(!route)return{};const title=`Xe Ghép ${route.origin} – ${route.destination}`;const description=`Đặt xe ${route.origin} đi ${route.destination}: xe ghép, bao xe 4–7 chỗ, đón tận nơi. Giá và thời gian tham khảo rõ ràng.`;return{title,description,alternates:{canonical:`/${route.slug}`},openGraph:{title,description,images:[]},twitter:{title,description,images:[]}}}
export default async function RouteDetail({params}:{params:Promise<{slug:string}>}){
  const{slug}=await params;const route=routes.find((item)=>item.slug===slug);if(!route)notFound();
  const faq=[{q:"Giá xe được tính như thế nào?",a:"Giá hiển thị là mức tham khảo cho bản demo. Phong Cách sẽ xác nhận giá chính xác trước chuyến đi."},{q:"Xe có đón tận nơi không?",a:"Có. Điểm đón và trả được thống nhất khi Phong Cách gọi xác nhận xe."},{q:"Nên đặt xe trước bao lâu?",a:"Bạn nên gửi yêu cầu sớm để Phong Cách chủ động tìm xe và giờ đón phù hợp."}];
  const jsonLd={"@context":"https://schema.org","@type":"FAQPage",mainEntity:faq.map((item)=>({"@type":"Question",name:item.q,acceptedAnswer:{"@type":"Answer",text:item.a}}))};
  const bookingUrl=`/?from=${encodeURIComponent(route.origin)}&to=${encodeURIComponent(route.destination)}#dat-xe`;
  return <main className="route-page"><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(jsonLd)}}/><header className="inner-header"><Link className="brand" href="/"><span className="brand-mark">PC</span><span><strong>PHONG CÁCH</strong><small>Xe ghép liên tỉnh</small></span></Link><a className="btn btn-primary" href="tel:0987663883">☎ Gọi đặt xe</a></header><section className="route-detail-hero"><div><Link href="/tuyen-xe">← Tất cả tuyến</Link><span>{route.tag||"Xe ghép mỗi ngày"}</span><h1>Xe Ghép {route.origin}<br/><b>– {route.destination}</b></h1><p>Đặt chuyến nhanh, đón tận nơi. Có xe 4 chỗ, 7 chỗ và bao xe theo nhu cầu.</p><div className="route-detail-actions"><a className="btn btn-primary" href={bookingUrl}>Đặt chuyến ngay →</a><a className="btn btn-ghost" href="tel:0987663883">Gọi 0987 663 883</a></div></div><aside><span>THÔNG TIN TUYẾN</span><div><small>Giá ghép tham khảo</small><strong>{route.sharedPrice?`Từ ${Math.round(route.sharedPrice/1000)}.000đ/người`:"Liên hệ báo giá"}</strong></div><div><small>Quãng đường</small><strong>Khoảng {route.distanceKm} km</strong></div><div><small>Thời gian di chuyển</small><strong>Khoảng {Math.floor(route.durationMinutes/60)} giờ {route.durationMinutes%60||""} phút</strong></div><p>Thời gian có thể chênh lệch 10–30 phút theo lịch đón khách.</p></aside></section><section className="route-info"><div><span className="section-kicker">DỄ ĐẶT, DỄ ĐI</span><h2>Chuyến xe phù hợp với bạn</h2><div className="route-benefits"><article><b>🚗</b><h3>Xe 4–7 chỗ</h3><p>Xe đời mới, phù hợp cá nhân và gia đình.</p></article><article><b>⌖</b><h3>Đón tận nơi</h3><p>Linh hoạt điểm đón và điểm trả theo tuyến.</p></article><article><b>✓</b><h3>Xác nhận rõ ràng</h3><p>Giá và giờ được chốt trước khi xe đón.</p></article></div></div><div className="faq"><span className="section-kicker">CÂU HỎI THƯỜNG GẶP</span><h2>Thông tin cần biết</h2>{faq.map((item)=><details key={item.q}><summary>{item.q}<span>＋</span></summary><p>{item.a}</p></details>)}</div></section><section className="final-cta"><div><span>XE GHÉP PHONG CÁCH</span><h2>Cần đặt tuyến này?</h2><p>Gửi yêu cầu, bên mình sẽ gọi xác nhận xe và giá.</p></div><a className="btn btn-white" href={bookingUrl}>Đặt xe ngay</a></section></main>
}
